server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portal_lis
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

#  datasource:
#    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
#    driver-class-name: oracle.jdbc.OracleDriver
#    username: portal_lis
#    password: PORTAL_LIS
#    max-active: 5000
#    min-idle: 50