server:
  port: 9090
spring:
  cache:
    ehcache:
      config: classpath:/ehcache.xml
    type: ehcache
  datasource:
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    driver-class-name: oracle.jdbc.OracleDriver
    username: portal_lis
    password: PORTAL_LIS
    max-active: 5000
    min-idle: 50
    filter:
      config:
        enabled: false
      validation-query: select 1 from dual
  messages:
    basename: classpath:i18n/messages
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss